TOKEN: abalabahaha
JWT_KEY: achoo

ACTIVE_GUILD_ID: 1234

SHORTCUT_CHANNEL_IDS:
    - 12345
    - 67890

MONITOR_CHANNEL_IDS:
    - 1234
    - 5678
    - 9012
    - 3456
    - 7890

WHITELIST_ROLE_ID: 4567

CLIENT_ID: 1234
CLIENT_SECRET: abcde
REDIRECT_URI: https://example.com/callback

